### ISSUE TITLE
RREF activities (Mod E)

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#112]
I see that you've added some more activities to break down RREF algorithm rather than offloading to a video. I think this makes sense (it was the only thing we offloaded outside class), but I think this is the first time I've seen these.

In E.17 I think I understand why you added "find a solution", but students were still all over the board on what I was looking for. I think if we replaced these examples with a system that has a unique solution, we'd eliminate a lot of cognitive overload.

In E.18 they are still learning the notation for describing row operations. To reinforce this, we could make it a sorting activity: give the 5 row operations (in the notation we want to establish) and have them sort them into the correct order.

E.19 has a lot of complexity I'd prefer split into several slides. Perhaps pivots should be defined and motivated on a separate slide (with both matrix & system showing). Then students can identify pivots for the current E.19 in an activity. Then RREF form is defined and motivated on a separate slide. Finally students identify RREFs as in the current E.19.

I'm still in the middle of them, but I think I'd prefer exchanging E.21-E.25 with a guided sequence of activities that ends up producing an RREF matrix (rather than a bunch of unrelated exercises).

**Comment by siwelwerd** [comment]
Yeah, forgot to mention that I added them in there. I haven't looked at these since the fall, but I thought they worked better than our original attempts and the offloading to the video. 

E.17: I am with you on reducing extraneous cognitive load. I think I just didn't want to have a system x=3, y=5 and say "Find a solution", which would be trivial.
E.18: I like it.
E.19: Agreed, but I like keeping the definition on the activity slide as a reminder. Otherwise they are flipping back and forth between slides. I did notice students have trouble later with what a "pivot" is, so maybe that would help.
E. 21-25: Yes, that would be better.

I'm going to run with them as-is tomorrow (and Friday for E.21-E.25) and post my fresh thoughts.

**Comment by StevenClontz** [comment]
E.17: I'm okay with the trivial x=3, y=5, z=7 I think. At this stage they still need discussion on what the goal of solving a system means.

I agree the definition should stay on E.19.

**Comment by siwelwerd** [comment]
I saw the cognitive load issues you mentioned with E.17 on Wednesday. Some groups did just fine, others skipped over the reduced system because they couldn't see how to "solve it" (by which I think they mean "find a unique solution"). My groups didn't have any issues with E.19 as written, though I think your suggestion would be an improvement nonetheless.
