### ISSUE TITLE
Module A Tweaks

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#121]
Activity A.28 should be presented like A.29 to reduce extraneous cognitive load. This was especially noticable after the two week layoff!

**Comment by siwelwerd** [comment]
I am wondering about changing standard A2 to be "Here is the standard matrix, now compute T(v)". Despite a high success rate on this standard, students have trouble in Module M when they need to do that to compose linear transformations.

**Comment by StevenClontz** [comment]
For A2 exercises, perhaps we just always give the function expression of the transformation and always ask (a) for the standard matrix, and (b) for T(v) to be computed specifically using the standard matrix? That removes a measurement of their ability to turn a standard matrix back into the transformation function, but maybe that's not as important as making sure they use the standard matrix directly.

Thinking more about A3, I think rewording to say "Explain how to find the image and kernel..." followed by "Then explain how to find a basis for the image and a basis for the kernel." While technically this is redundant with earlier standards, I think it's worth the reinforcement (so they connect their reasoning to the actual objects, rather than just matrix features).

**Comment by siwelwerd** [comment]
Maybe on A2 just provide two maps. Give T as a function expression, and ask for the standard matrix. Give a standard matrix for S, and ask for S(v) for some vector v.

**Comment by siwelwerd** [comment]
We really don't explicitly hit the rank nullity theorem in module A (we could probably add a single activity to do so -- the proof is dim(Im T)= # pivot columns , dim(ker T) = # non pivot columns, dim(domain)=# of columns). I am wondering if we should add such an activity, and add a part (c) to A3, that asks them to verify that the rank-nullity theorem holds for that particular map.

**Comment by StevenClontz** [comment]
I think this is worthwhile.

**Comment by siwelwerd** [comment]
A3 (c): "Explain how to find the rank and nullity of T, and why the rank-nullity theorem holds for T".
