### ISSUE TITLE
Fall 2018 Feedback

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#83]
Hopefully this won't be so broad as to need multiple issues, but feedback from Jared/Selvi should be documented here.

**Comment by selvikara** [comment]
Correction:

- Module V, Activity V.1.6, Part 1: Show that 1 "is" the scalar multiplication ...



Suggestion: 

- Module V, Definition V.0.3: adding the names of properties such as associativity of addition, commutativity, additive identity element, additive inverse, associativity of scalar multiplication, scalar multiplication identity, etc.. 

- Module V, Activity V.1.6, Part 1: If we change the statement of the activity as "Find the scalar multiplication identity satisfying $c \odot (x,y) =(x,y)$ by working out the equality $c \odot (x,y) =(x,y)$. ", it would be more in line with the previous activity and give them an idea on how to actually find the scalar multiplication identity. 

-Module V, Activity V.1.6, Part 2: Rewording of the statement "Show that V fails the addition identity property $\vec{v} \oplus \vec{z} =\vec{v}$ by showing that $(0,-1) \oplus \vec{z} \new (0,-1)$ no matter how $\vec{z}=(zz_1,_2)$ is chosen."

**Comment by siwelwerd** [comment]
Summarizing the feedback from today's meeting with @selvikara and @JaredHolshouser 

- Standard M4 duplicated G1; rather than have it as a separate standard, it should be addressed in the Module G RAT.  Standard G1 should be modified to have students compose two row operations.
- The fact that matrices (as a generalization of Euclidean vectors) are a vector space should be introduced early on.
- In order to make the materials easier to use by a broader set of instructors, the slides should be flattened (i.e. "parts" or "sections" removed), with the expectation that individual instructors would partition them up based on their class session length.
- Standard A1 problems had uneven difficulty levels--problems about polynomials should not use expressions like ax^2+bx+c.
- Similarly, V4 has problems of varying difficulty as well.
- Solutions should be removed from the exercise library, leaving only the answers for students to check their work.  A fully worked example of each standard is located in the sample assessment file.

**Comment by siwelwerd** [comment]
Rename Standard V9.  Maybe "Polynomial basis computation".

**Comment by siwelwerd** [comment]
I addressed most of these, and split the rest out into #84 and #85 .
